Feature/nq fix friend api
quinxii/AlumverseHcmusBackend pull request #101
Opened 2024-07-07 15:40 UTC by quinxii

Fix Profile API, Friend API.
Create new Random Hof API.

2024-07-07 17:23 UTC, mugetsu0422 requested changes

2024-07-07 17:23 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/repository/FriendRepository.java
> +		       "WHERE (f.id.userId = :userId OR f.id.friendId = :userId) " +
ở chỗ accept friend request b lưu 2 record A có friend B và B có friend A r thì nếu muốn lấy friend của A thì lấy `f.id.userId = :userId` là dc r mà nhỉ

2024-07-07 17:23 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/repository/FriendRepository.java
> +			+ "where (f.user_id = :userId or f.friend_id = :userId)and f.is_delete = false", nativeQuery = true)
như trên

2024-07-07 17:23 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/repository/FriendRepository.java
mấy cái check thêm phía friendId ngược lại thì số kq trả về sẽ nhân đôi

2024-07-07 17:34 UTC, quinxii commented on user-service/src/main/java/hcmus/alumni/userservice/repository/FriendRepository.java
> +		       "WHERE (f.id.userId = :userId OR f.id.friendId = :userId) " +
tui quên xóa đoạn lưu 2 record nha

2024-07-07 17:38 UTC, quinxii commented on user-service/src/main/java/hcmus/alumni/userservice/repository/FriendRepository.java
tui đã loại bỏ vụ lưu 2 record lúc accept friend request thì comment này không cần nữa ông nhỉ

2024-07-08 03:22 UTC, mugetsu0422 requested changes
chỉnh mấy cái như t nhắn trong group nha

2024-07-09 14:41 UTC, mugetsu0422 approved these changes

2024-07-09 14:41 UTC, merged