CN events
quinxii/AlumverseHcmusBackend pull request #13
Opened 2024-04-08 19:14 UTC by HuynhNguyen0811

2024-04-09 03:35 UTC, mugetsu0422 reviewed
Thêm TagModel vô đi ô, tham khảo thêm ntn bên nhánh t
Tạo Interface DTO để chỉ trả về những dữ liệu cần thiết cho user

2024-04-09 04:21 UTC, mugetsu0422 requested changes

2024-04-09 04:21 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
> +                                                  @RequestParam(required = false) Integer views) {
update view làm gì v ô :(
tăng view có thể thực hiện ở get 1 event cụ thể nếu tìm thấy

2024-04-09 04:21 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
> +                }
như trên khai báo Date trên request param lun

2024-04-09 04:21 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
> +                    existingEvent.setStatusId(statusPostOptional.get());
như trên
t new thẳng theo id lun

2024-04-09 04:21 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
> +                existingEvent.setViews(views);
```suggestion
```
bỏ

2024-04-09 04:21 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
> +}
như trên

2024-04-09 04:21 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/model/EventModel.java
thêm Tag

2024-04-09 04:21 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/model/EventModel.java
> +    @GeneratedValue(strategy = GenerationType.UUID)
```suggestion
```
nếu dùng này thì sẽ ko có id để lưu ảnh

2024-04-09 04:21 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/model/RoleModel.java
bên event cần gì tới role của user. bỏ

2024-04-09 04:21 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/model/SexModel.java
như Role. bỏ
chỉnh lại bên UserModel như này
	@Column(name = "sex_id")
	private Integer sex;

2024-04-09 04:21 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/model/UserModel.java
> +    private Set<RoleModel> roles = new HashSet<>();
ko cần. bỏ
```suggestion

```

2024-04-09 04:21 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/model/UserModel.java
> +	private SexModel sex;
```suggestion
```
data ko cần thì ko cần join. để column theo nhận xét trên

2024-04-09 04:21 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/model/UserModel.java
> +	private FacultyModel faculty;
như trên

2024-04-09 04:21 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/repository/EventRepository.java
dùng Projection

2024-04-09 04:21 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/utils/ImageUtils.java
> +	private final String noneAvatar = "none";
```suggestion
```
ko dùng thì xóa

2024-04-09 04:21 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/utils/ImageUtils.java
> +	private final String avatarPath = "images/event/thumbnail/";
```suggestion
	private final String eventPath = "images/events/";
```

2024-04-09 04:21 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/utils/ImageUtils.java
> +		}
```suggestion
```

2024-04-09 04:21 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/utils/ImageUtils.java
> +	}
```suggestion
	public String getEventsPath(String id) {
		return eventsPath + id + "/";
	}
```

2024-04-09 04:21 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/utils/ImageUtils.java
ảnh sẽ lưu theo path sau
images/events/{id}/

2024-04-09 04:21 UTC, mugetsu0422 commented on event-service/src/main/resources/application.properties
> +server.port=9001
9001 trùng với user-service r
```suggestion
server.port=9004
```

2024-04-09 04:21 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
> +                    String imageName = ImageUtils.hashImageName(eventId);
```suggestion
```
ko cần hash, tên là id của event

2024-04-09 15:02 UTC, HuynhNguyen0811 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
> +            }
à cái này là id của người tạo event á

2024-04-09 16:00 UTC, mugetsu0422 reviewed
quên mất cái này, thêm phân quyền vô đi ô

2024-04-14 01:32 UTC, mugetsu0422 requested changes

2024-04-14 01:32 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
> +	    }
ko có lên lịch, post thì mặc định là "Bỉnh thường"

2024-04-14 01:32 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
> +	@PutMapping("/{id}/content")
content event chỉ có plain text thôi, ko có hình
gộp lên post với put đi ô

2024-04-14 01:32 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
> +	        String newContent = imageUtils.updateImgFromHtmlToStorage(event.getContent(), updatedEvent.getContent(), id);
```suggestion
```
ko có hình

2024-04-14 01:32 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/model/EventModel.java
> +    private Integer views = 0;
với event thì views t nghĩ nên thay bằng số người tham gia
lên group nhờ nduy đổi thành số người tham gia đi ô

2024-04-14 01:32 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
> +	@GetMapping("/")
thêm request param search theo khoa đi ô
[tham khảo](https://stackoverflow.com/questions/70165854/spring-data-jpa-how-to-form-a-conditional-query)

2024-04-14 01:33 UTC, mugetsu0422 reviewed
update file excel Danh sách API lun nha ô

2024-04-14 13:52 UTC, HuynhNguyen0811 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
> +	@PutMapping("/{id}/content")
oke

2024-04-14 13:54 UTC, HuynhNguyen0811 commented
> update file excel Danh sách API lun nha ô

tui tính là khi nào merge vô xong rồi mới chỉnh excel á

2024-04-14 13:59 UTC, mugetsu0422 commented
> > update file excel Danh sách API lun nha ô
> 
> tui tính là khi nào merge vô xong rồi mới chỉnh excel á

v update file excel xong báo trên gr để bên fe ghép api nha ô

2024-04-14 17:10 UTC, HuynhNguyen0811 commented on event-service/src/main/java/hcmus/alumni/event/model/EventModel.java
> +    private Integer views = 0;
Nhắc mới nhớ là người tham gia thì có cái bảng riêng, để tui thêm cái đó vô mấy cái trả về của Get API
Còn views thì tui nghĩ vẫn nên giữ chứ nhỉ

2024-04-15 03:10 UTC, mugetsu0422 requested changes

2024-04-15 03:10 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
> +	        events = eventRepository.searchEvents(title, statusId, facultyId, pageable);
lấy thêm số người tham gia như Get {id} đi ô

2024-04-15 03:10 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/model/ParticipantEventId.java
bảng này là sao v ô

2024-04-15 03:10 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/repository/EventRepository.java
> +	        "GROUP BY e.id")
ko có count gì hết sao group by ô

2024-04-15 03:13 UTC, HuynhNguyen0811 commented on event-service/src/main/java/hcmus/alumni/event/model/ParticipantEventId.java
à cái Participant Event nó có khóa chính là 2 cái event_id với user_id, tui thấy trên mạng chỉ là dùng Embedded như này

2024-04-15 03:18 UTC, HuynhNguyen0811 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
> +	        events = eventRepository.searchEvents(title, statusId, facultyId, pageable);
lấy thêm số người tham gia cho cái get danh sách này tui không biết làm sao á :(( tối qua ngồi mò mà không biết chỉnh sao cho được

2024-04-15 03:18 UTC, HuynhNguyen0811 commented on event-service/src/main/java/hcmus/alumni/event/repository/EventRepository.java
> +	        "GROUP BY e.id")
hôm qua ngồi mò cái count quên xóa :((

2024-04-15 04:07 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
> +	        events = eventRepository.searchEvents(title, statusId, facultyId, pageable);
v thì chỉnh views thành số lượng ng tham gia thôi ô

2024-04-15 04:39 UTC, HuynhNguyen0811 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
> +	        events = eventRepository.searchEvents(title, statusId, facultyId, pageable);
oke vậy để nhắn lên gr

2024-04-15 16:33 UTC, merged