Feature/nq hall of fame
quinxii/AlumverseHcmusBackend pull request #15
Opened 2024-04-14 23:46 UTC by quinxii

hall of fame apis done

2024-04-15 00:30 UTC, quinxii commented
close

2024-04-15 00:31 UTC, quinxii commented
hof apis

2024-04-15 03:27 UTC, HuynhNguyen0811 commented
🫠nhiều file nhỉ

2024-04-15 03:30 UTC, HuynhNguyen0811 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/controller/HallOfFameServiceController.java
> +	}
Này nên có lọc theo faculty luôn nhỉ

2024-04-15 03:31 UTC, HuynhNguyen0811 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/controller/HallOfFameServiceController.java
> +	public ResponseEntity<Long> getPendingAlumniVerificationCount(@RequestParam(value = "status") String status) {
Chưa đổi tên này

2024-04-15 03:32 UTC, HuynhNguyen0811 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/controller/HallOfFameServiceController.java
> +//
xóa này i để clean

2024-04-15 03:36 UTC, HuynhNguyen0811 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/dto/HallOfFameDto.java
> +//	private String content;
xóa này i để clean

2024-04-15 03:36 UTC, HuynhNguyen0811 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/dto/HallOfFameDto.java
> +//	private String content;
xóa này i để clean

2024-04-15 03:38 UTC, HuynhNguyen0811 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/model/HallOfFameModel.java
> +	@JoinTable(name = "tag_news", joinColumns = @JoinColumn(name = "news_id"), inverseJoinColumns = @JoinColumn(name = "tag_id"))
còn để tag news này

2024-04-15 03:39 UTC, HuynhNguyen0811 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/controller/HallOfFameServiceController.java
cái hof tui thấy nhiều trường vậy mà api update với add ít vậy thôi á

2024-04-15 03:42 UTC, HuynhNguyen0811 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/utils/ImageUtils.java
file này chưa đổi lại tên cho biến với hàm này, còn thấy để là news

2024-04-15 03:58 UTC, mugetsu0422 requested changes

2024-04-15 03:58 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/controller/HallOfFameServiceController.java
> +			@RequestParam(value = "title", required = false, defaultValue = "Nguyen Nhat Quynh2") String title,
```suggestion
			@RequestParam(value = "title", required = false, defaultValue = "Nguyen Nhat Quynh2") String title,
```
```suggestion
			@RequestParam(value = "title", required = false, defaultValue = "") String title,
```

2024-04-15 03:58 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/controller/HallOfFameServiceController.java
> +			@RequestParam(value = "title") String title, @RequestParam(value = "content") String content,
```suggestion
			@RequestParam(value = "title") String title,
```
có put content ở dưới r nên ko cần này đâu

2024-04-15 03:58 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/controller/HallOfFameServiceController.java
> +				}
thumbnail của hof trong db null thì liên quan gì tới upload nhiều ảnh nhỉ.
phần khai báo `@RequestParam(value = "thumbnail", required = false) MultipartFile thumbnail` ở trên là mặc định lấy 1 file r dù cho có chọn nhiều file

2024-04-15 03:58 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/controller/HallOfFameServiceController.java
> +	    halloffameRepository.deleteById(id);
khúc này set lại status á, đừng delete

2024-04-15 03:58 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/dto/IHallOfFameDto.java
> +    Set<Tag> getTags();
```suggestion
```
hof ko có tag

2024-04-15 03:58 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/model/HallOfFameModel.java
> +	private Set<TagModel> tags = new HashSet<>();
```suggestion
```
hof có ko tag

2024-04-15 03:58 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/model/HallOfFameModel.java
> +	}
```suggestion
```
như trên

2024-04-15 03:58 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/model/TagModel.java
hof ko có tag
chỉ có news, event, tư vấn và post trong group là có

2024-04-15 03:58 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/controller/HallOfFameServiceController.java
thêm 1 api tăng views hoặc tăng views trong get {id} nha

2024-04-15 03:58 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/controller/HallOfFameServiceController.java
> +	@GetMapping("")
bữa thấy UI hof của nduy có search theo khoa với khoá nên b thêm request param để search theo khoa với khoá nha

2024-04-15 03:58 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/repository/HallOfFameRepository.java
> +	Page<IHallOfFameDto> searchHofByStatus(String title, Integer statusId, Pageable pageable);
thêm search theo khoa với khoá
[tham khảo](https://stackoverflow.com/questions/70165854/spring-data-jpa-how-to-form-a-conditional-query)

2024-04-15 03:58 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/controller/HallOfFameServiceController.java
> +			@RequestParam(value = "beginningYear") Integer beginningYear) {
```suggestion
			@RequestParam(value = "beginningYear") Integer beginningYear), @RequestParam(value = "scheduledTime", required = false) Long scheduledTimeMili) {
```
thấy có làm lên lịch mà ở đây thiếu cái schudule

2024-04-15 03:58 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/utils/ImageUtils.java
> +	private final String newsPath = "images/news/";
```suggestion
	private final String hofPath = "images/hof/";
```

2024-04-15 03:58 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/utils/ImageUtils.java
> +	}
```suggestion
	public String getHofPath(String id) {
		return this.hofPath + id + "/";
	}
```

2024-04-16 01:32 UTC, mugetsu0422 requested changes

2024-04-16 01:32 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/controller/HallOfFameServiceController.java
> +			halloffameRepository.save(halloffame);
ko xử lý lên lịch hả
scheduledTime != null thì set status là Chờ với set publishAt là Date của scheduledTime

2024-04-16 01:32 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/controller/HallOfFameServiceController.java
> +		}
else thì return lỗi email ko tồn tại đi

2024-04-16 01:32 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/controller/HallOfFameServiceController.java
> +				String userId = halloffameRepository.getUserIdByEmail(emailOfUser);
ko tồn tại thì trả về lỗi

2024-04-16 01:32 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/repository/HallOfFameRepository.java
> +	Page<IHallOfFameDto> searchHofByStatusAndBeginningYear(@Param("title") String title, @Param("statusId") Integer statusId, @Param("beginningYear") Integer beginningYear, Pageable pageable);
8 cái này gộp lại dc mà. có 1 cái cmt t có gửi link tham khảo á

2024-04-16 01:32 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/utils/ImageUtils.java
> +				String newSrc = this.saveBase64ImageToStorage(this.getNewsPath(id), src, contentImgIdx.toString());
ko sửa lại thành của hof v :(

2024-04-16 01:32 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/utils/ImageUtils.java
> +					String newSrc = this.saveBase64ImageToStorage(this.getNewsPath(id), addedImg, newIdx);
như trên, sửa lại thành của hof

2024-04-16 01:32 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/utils/ImageUtils.java
> +	}
```suggestion
```

2024-04-16 01:32 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/utils/ImageUtils.java
> +	private final String newsPath = "images/news/";
```suggestion
```

2024-04-16 01:32 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/repository/HallOfFameRepository.java
> +	Page<IHallOfFameDto> searchHofByStatusAndBeginningYear(@Param("title") String title, @Param("statusId") Integer statusId, @Param("beginningYear") Integer beginningYear, Pageable pageable);
phần search bên cn, có gì tham khảo nha
`	@Query("SELECT e " +
        "FROM EventModel e " +
        "LEFT JOIN e.status s " +
        "LEFT JOIN e.faculty f " +
        "WHERE (:statusId IS NULL OR s.id = :statusId) " +
        "AND (:facultyId IS NULL OR f.id = :facultyId) " +
        "AND e.title LIKE %:title%")
	Page<IEventDto> searchEvents(@Param("title") String title, @Param("statusId") Integer statusId, @Param("facultyId") Integer facultyId, Pageable pageable);`

2024-04-16 01:32 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/controller/HallOfFameServiceController.java
> +            }
💀
gộp lại đi, xem cmt dưới phần service
có thể tham khảo search của event

2024-04-16 01:40 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/controller/HallOfFameServiceController.java
> thêm 1 api tăng views hoặc tăng views trong get {id} nha

@quinxii

2024-04-17 02:13 UTC, mugetsu0422 requested changes

2024-04-17 02:13 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/controller/HallOfFameServiceController.java
> +}
```suggestion
	public ResponseEntity<IHallOfFameDto> getHallOfFameById(@PathVariable String id) {
	    Optional<IHallOfFameDto> halloffame = halloffameRepository.findById(id);
	    return halloffame.map(ResponseEntity::ok)
	        .orElseGet(() -> ResponseEntity.status(HttpStatus.NOT_FOUND).build());
	}
}
```
dùng hàm viewsIncrement để tăng views nếu tìm thấy

2024-04-17 02:13 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/controller/HallOfFameServiceController.java
> +				String userId = halloffameRepository.getUserIdByEmail(emailOfUser);
```suggestion
				String userId = halloffameRepository.getUserIdByEmail(emailOfUser);
				if (userId.isEmpty()) {
					return ResponseEntity.status(HttpStatus.NOT_FOUND).body("User not existed");
				}
```
thấy tim mà ko xử lý nếu ko tìm dc userid v :(

2024-04-17 02:28 UTC, mugetsu0422 commented on hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/controller/HallOfFameServiceController.java
> +            @RequestParam(value = "beginningYear", required = false, defaultValue = "") Integer beginningYear) {
```suggestion
            @RequestParam(value = "statusId", required = false) Integer statusId,
            @RequestParam(value = "facultyId", required = false) Integer facultyId,
            @RequestParam(value = "beginningYear", required = false, defaultValue = "0") Integer beginningYear) {
```
bỏ defaultValue để nếu ko có thì sẽ là null. qua đó tận dụng dc câu query để ko search theo status hoặc faculty

2024-04-17 15:15 UTC, mugetsu0422 approved these changes

2024-04-18 03:06 UTC, merged