CN events addition api
quinxii/AlumverseHcmusBackend pull request #17
Opened 2024-04-18 10:23 UTC by HuynhNguyen0811

get most participants and hot events api

2024-04-18 13:45 UTC, mugetsu0422 requested changes
cái api get list thêm option lấy từ hiện tại trở đi đi ô

2024-04-18 13:45 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
> +	@GetMapping("/most-participants")
```suggestion
	@GetMapping("/most-participated")
```

2024-04-18 13:45 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
> +	@GetMapping("/hot")
cũng lấy theo participant thì khác gì ở trên ô
bỏ cái trên đi

2024-04-18 13:45 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
> +	    Date startDate = cal.getTime();
copy mà ko thèm chỉnh gì v ô :(
sự kiện thì chỉ cần startDate là hiện tại

2024-04-18 13:45 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/repository/EventRepository.java
> +    Page<IEventDto> getHotEvents(Date startDate, Date endDate, Pageable pageable);
lấy từ hiện tại trở đi

2024-04-18 17:18 UTC, HuynhNguyen0811 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
> +	    Date startDate = cal.getTime();
ừ ha :( tui vô tri

2024-04-19 02:03 UTC, mugetsu0422 commented
> cái api get list thêm option lấy từ hiện tại trở đi đi ô

này để sau hả ô

2024-04-19 02:03 UTC, mugetsu0422 approved these changes

2024-04-19 03:40 UTC, merged