CN events comments and participants
quinxii/AlumverseHcmusBackend pull request #20
Opened 2024-04-21 22:12 UTC by HuynhNguyen0811

1. đổi search events default lấy event từ hiện tại trở đi (có thể lấy all từ trước đến giờ)
2. chỉnh get danh sách participants lấy theo trang
3. thêm api cho user tham gia và bỏ tham gia sự kiện
4. thêm api get, add, update, delete cho events comments
5. clean

2024-04-22 10:42 UTC, mugetsu0422 requested changes
thêm api lấy list event mà ng dùng tham gia đi ô
lấy theo event đã diễn ra và sẽ diễn ra

2024-04-22 10:42 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
> +	    eventRepository.participantCountIncrement(id, -1);
có trigger r mà ô

2024-04-22 10:42 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
> +	        @RequestParam(value = "note", required = false) String note) {
ko có file thì dùng RequestBody

2024-04-22 11:07 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/repository/CommentEventRepository.java
> +	@Query("UPDATE CommentEventModel c SET c.isDelete = true WHERE c.parentId = :parentId")
```suggestion
	@Query("UPDATE CommentEventModel c SET c.isDelete = true WHERE c.parentId = :parentId AND c.isDelete = false")
```
thêm đk để ko đếm những thằng đã xoá

2024-04-23 14:03 UTC, HuynhNguyen0811 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
> +	    eventRepository.participantCountIncrement(id, -1);
có trigger cho add với delete, nhưng cái này là update isDelete = true

2024-04-24 00:47 UTC, mugetsu0422 requested changes

2024-04-25 02:39 UTC, mugetsu0422 approved these changes
còn cái api sự kiện liên quan mà nduy kêu á ô
nhma t thấy sự kiện thì lâu lâu mới có nên khả năng cao là lúc lấy data thì sẽ ko có gì hết 💀. Sự kiện bth đã hiếm r, lấy cùng khoa hoặc tag nó còn hiếm hơn. Này lên gr bàn thêm đi ô.

2024-04-25 02:42 UTC, mugetsu0422 requested changes
nhầm approve :(

2024-04-25 08:48 UTC, mugetsu0422 approved these changes
khỏi sự kiện liên quan đi ô

2024-04-25 14:20 UTC, merged