CN group
quinxii/AlumverseHcmusBackend pull request #24
Opened 2024-04-24 19:27 UTC by HuynhNguyen0811

1. Groups management
- Get(""): Searches groups
- Get("/{id}"): Gets a specific group
- Get("/joined-groups"): List of joined group
- Post(""): Adds a groups
- Put(""): Updates a group
- Delete(""): Deletes a group

2. Groups member
- Get("/{id}/members"): List of members of a group
- Put("/{id}/members/{userId}"): Updates role of member
- Delete("/{id}/members/{userId}"): Kicks member

3. Request join
- Get("/{id}/requests"):  List of request join of a group
- Post("/{id}/requests"): Adds a request join
- Put("/{id}/requests/{userId}"): Approves or denies request join. If approve then add member. Always delete request join after decision.

4. Post group
- Get("{id}/posts"):  List of post group of a group
- Get("/posts/{postId}"): Gets a specific post group
- Post("{id}/posts"): Adds a post group
- Put"/posts/{postId}"): Updates a post group
- Delete("/posts/{postId}"): Deletes a post group

5. Comment post group
- Get("/{id}/comments"): Retrieves all comments belonging to a particular post group.
- Get("/comments/{commentId}/children"): Gets child comments (replies) for a specific comment.
- Post("/{id}/comments"): Adds a comment.
- Put("/comments/{commentId}"): Updates a comment.
- Delete("/comments/{commentId}"): Deletes a comment.

2024-04-25 04:30 UTC, mugetsu0422 requested changes

2024-04-25 04:30 UTC, mugetsu0422 commented on group-service/src/main/java/hcmus/alumni/group/controller/GroupServiceController.java
> +    @PostMapping("{id}/posts")
Hôm qua họp thì có bàn về cái post trong group và bài tư vấn thì nó sẽ như fb.
content là plain text. Sẽ có 1 bảng riêng để lưu url ảnh của các post. Tối đa sẽ có 5 ảnh 1 post, khúc này check if else là dc.
Này tạm thời để đó đi để t suy nghĩ cách xử lý ảnh r qua nhánh t copy

2024-04-25 04:30 UTC, mugetsu0422 commented on group-service/src/main/java/hcmus/alumni/group/model/GroupMemberModel.java
> +    @EmbeddedId
vừa dùng EmbeddedId vừa dùng JoinColumn cho 2 cái y chang nhau là sao ô.
1 là bỏ EmbeddedId và dùng `@Id` cho 2 cái JoinColumn ở dưới
2 là [này](https://docs.oracle.com/javaee/6/api/javax/persistence/MapsId.html)
[Composite Primary Key](https://www.baeldung.com/jpa-composite-primary-keys)

2024-04-25 04:30 UTC, mugetsu0422 commented on group-service/src/main/java/hcmus/alumni/group/model/RequestJoinGroupModel.java
> +	@EmbeddedId
như trên

2024-04-25 04:30 UTC, mugetsu0422 commented on group-service/src/main/resources/application.properties
> +server.port=9006
```suggestion
server.port=9007
```

2024-04-25 05:59 UTC, HuynhNguyen0811 commented on group-service/src/main/java/hcmus/alumni/group/controller/GroupServiceController.java
> +            @RequestParam(value = "website", required = false, defaultValue = "") String website,
tui không biết nữa, thấy có trong db nên để đó :((

2024-04-25 05:59 UTC, HuynhNguyen0811 commented on group-service/src/main/java/hcmus/alumni/group/controller/GroupServiceController.java
> +    @PostMapping("{id}/posts")
oke :Đ

2024-04-29 20:35 UTC, HuynhNguyen0811 commented
Khi nào cái này oke rồi thì tui mới update excel

2024-04-30 02:54 UTC, mugetsu0422 approved these changes

2024-04-30 04:35 UTC, merged