CN fix events api
quinxii/AlumverseHcmusBackend pull request #27
Opened 2024-04-26 17:08 UTC by HuynhNguyen0811

1. Get events and Get participated events: isUpcoming > mode: 1 get future, 2 get past, 3 get all
2. Create event and Update event: Can minimum and maximum participants when create and edit an event

2024-04-26 23:45 UTC, mugetsu0422 requested changes
ko fix cái lỗi ở ParticipantEventRepository hả ô
Expected Domain ID type is 'hcmus.alumni.event.model.ParticipantEventId'vscode-spring-boot(DOMAIN_ID_FOR_REPOSITORY)
cho cái tham số String thành ParticipantEventId

2024-04-26 23:53 UTC, HuynhNguyen0811 commented
> ko fix cái lỗi ở ParticipantEventRepository hả ô Expected Domain ID type is 'hcmus.alumni.event.model.ParticipantEventId'vscode-spring-boot(DOMAIN_ID_FOR_REPOSITORY) cho cái tham số String thành ParticipantEventId

Lúc hqua tui test bằng eclipse thì không bị lỗi này á :(

2024-04-27 00:21 UTC, mugetsu0422 commented
> > ko fix cái lỗi ở ParticipantEventRepository hả ô Expected Domain ID type is 'hcmus.alumni.event.model.ParticipantEventId'vscode-spring-boot(DOMAIN_ID_FOR_REPOSITORY) cho cái tham số String thành ParticipantEventId
> 
> Lúc hqua tui test bằng eclipse thì không bị lỗi này á :(

bên vscode nó báo lỗi ô
tham số thứ 2 phải là Id của Entity tức là cái cục ParticipantEventId chứ ko phải String

2024-04-27 00:30 UTC, HuynhNguyen0811 commented
> > > ko fix cái lỗi ở ParticipantEventRepository hả ô Expected Domain ID type is 'hcmus.alumni.event.model.ParticipantEventId'vscode-spring-boot(DOMAIN_ID_FOR_REPOSITORY) cho cái tham số String thành ParticipantEventId
> > 
> > 
> > Lúc hqua tui test bằng eclipse thì không bị lỗi này á :(
> 
> bên vscode nó báo lỗi ô tham số thứ 2 phải là Id của Entity tức là cái cục ParticipantEventId chứ ko phải String

Oke, tui mới chỉnh á, ông coi xem đúng không, Nếu vậy thì bên group cũng sẽ bị lỗi y chang như này

2024-04-27 00:43 UTC, merged