CN Fix logic Event and Group + Add React Post Group
quinxii/AlumverseHcmusBackend pull request #39
Opened 2024-05-11 20:02 UTC by HuynhNguyen0811

1. Mostly fix Group apis' conditions
2. Fix Event apis
3. Add React Post Group (copied from Counsel)
Note: update excel after merge

2024-05-12 02:47 UTC, mugetsu0422 requested changes

2024-05-12 02:47 UTC, mugetsu0422 commented on group-service/src/main/java/hcmus/alumni/group/controller/GroupServiceController.java
> +        //create request if group is private, auto join as member if group is public
group công khai ko cần duyệt hả ô

2024-05-12 02:47 UTC, mugetsu0422 commented on group-service/src/main/java/hcmus/alumni/group/model/PostGroupModel.java
> +	private boolean isReacted;
ko dùng new Constructor ở cái Query của search postGroup để tạo giá trị cho thằng này hả ô

2024-05-12 02:47 UTC, mugetsu0422 commented on group-service/src/main/java/hcmus/alumni/group/repository/PostGroupRepository.java
[set giá trị cho Transient fields đi ô](https://stackoverflow.com/questions/25674033/set-transient-value-from-database-with-spring-data-jpa)

2024-05-12 07:33 UTC, HuynhNguyen0811 commented on group-service/src/main/java/hcmus/alumni/group/controller/GroupServiceController.java
> +        //create request if group is private, auto join as member if group is public
tui thấy trên fb thì group public nhấn join là vô luôn, post thì coi được không cần là member. Còn group private thì mới cần duyệt, mấy bài post thì cần là member mới được coi

2024-05-12 09:39 UTC, mugetsu0422 commented on group-service/src/main/java/hcmus/alumni/group/controller/GroupServiceController.java
> +        //create request if group is private, auto join as member if group is public
ok

2024-05-13 01:00 UTC, mugetsu0422 approved these changes
nhớ chỉnh excel nha ô

2024-05-13 15:28 UTC, merged