Feature/nq admin create update user account
quinxii/AlumverseHcmusBackend pull request #50
Opened 2024-05-26 16:06 UTC by quinxii

2024-05-27 04:53 UTC, mugetsu0422 requested changes

2024-05-27 04:53 UTC, mugetsu0422 commented on auth-service/src/main/java/hcmus/alumni/authservice/controller/AuthController.java
> +	public ResponseEntity<String> resetPassword(@RequestParam String email, @RequestParam String oldPassword, @RequestParam String newPassword) {
```suggestion
	public ResponseEntity<String> resetPassword(@RequestBody ResetPasswordRequestDto req) {
```
Nên dùng `@RequestBody` thay vì `@RequestParam` cho những api ko xử lý file. Dùng request body sẽ ko bị giới hạn bởi url max length, hỗ trợ các cấu trúc phức tạp
B tạo folder `dto` chứa file ResetPasswordRequestDto. File đó sẽ như này
```
@AllArgsConstructor
@NoArgsConstructor
@Data
public class ResetPasswordRequestDto implements Serializable {
    private static final long serialVersionUID = 1L;

    String email;
    String oldPassword;
    String newPassword;
}
```
Spring sẽ tự động map body của request thành class tương ứng

2024-05-27 04:53 UTC, mugetsu0422 commented on auth-service/src/main/java/hcmus/alumni/authservice/controller/AuthController.java
> +	                        .body(Collections.singletonMap("msg", "Vui lòng đổi mật khẩu của bạn"));
```suggestion
	                        .body(Collections.singletonMap("forcePasswordChange", true));
```

2024-05-27 04:53 UTC, mugetsu0422 commented on auth-service/src/main/java/hcmus/alumni/authservice/model/PasswordHistoryModel.java
> +    @Column(name = "updated_at")
```suggestion
    @UpdateTimestamp
    @Column(name = "updated_at")
```
tự động cập nhật thời gian khi insert/ update data

2024-05-27 04:53 UTC, mugetsu0422 commented on auth-service/src/main/java/hcmus/alumni/authservice/controller/AuthController.java
chưa có trả về quyền của người dùng đăng nhập
khi đăng nhập thành công (ko tính tk dc cấp) thì sẽ trả về
```
{
    "jwt": "foo",
    "permissions": [
        {
            "name": "bar"
        },
        {
            "name": "baz"
        }
    ]
}
```

2024-05-27 04:53 UTC, mugetsu0422 commented on auth-service/src/main/java/hcmus/alumni/authservice/utils/JwtUtils.java
> +	public String generateForgotPwdToken(String email) {
cái này để làm gì v

2024-05-27 04:53 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java
> +	@PostMapping("/create-user")
```suggestion
	@PostMapping("")
```

2024-05-27 04:53 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java
> +            @RequestParam String fullName) {
```suggestion
    public ResponseEntity<String> adminCreateUser(
            @RequestBody UserModel req) {
```
dùng `@RequestBody` r sau đó lọc lại chỉ lấy email, role, và fullName

2024-05-27 04:53 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java
> +        newUser.setCreateAt(new Date());
```suggestion
```
đã có annotation `CreationTimestamp`

2024-05-27 04:53 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java
> +        newUser.setFullName(fullName);
```suggestion
        UserModel newUser = new UserModel();
        newUser.setId(UUID.randomUUID().toString());
        newUser.setEmail(req.getEmail());
        String pwd = UserConfig.generateRandomPassword(10);
        newUser.setPass(passwordEncoder.encode(pwd));
        newUser.setFullName(req.getfullName());
```

2024-05-27 04:53 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java
> +        newUser.getRoles().add(roleModel);
lấy id của roles từ req r add vô newUser

2024-05-27 04:53 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/model/PasswordHistoryModel.java
> +    @Column(name = "updated_at")
```suggestion
    @UpdateTimestamp
    @Column(name = "updated_at")
```

2024-05-27 04:53 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java
> +	@PreAuthorize("hasAnyAuthority('User.Edit')")
admin thì chỉ nên khoá/ bỏ khoá tài khoản 🤔
chỉnh sửa thế này can thiệp vô sâu quá

2024-05-27 16:23 UTC, quinxii commented on auth-service/src/main/java/hcmus/alumni/authservice/controller/AuthController.java
chỗ permissions này mình sẽ trả về cột name trong bảng permission đúng kh ông hay description é

2024-05-27 16:30 UTC, mugetsu0422 commented on auth-service/src/main/java/hcmus/alumni/authservice/controller/AuthController.java
trả về name nha

2024-05-29 15:05 UTC, mugetsu0422 requested changes

2024-05-30 10:42 UTC, mugetsu0422 approved these changes
nhớ update file excel api nha
mấy lần sau commit code đừng có commit từng file 😔, Với đặt tên commit có ý nghĩa.

2024-05-31 01:18 UTC, mugetsu0422 approved these changes

2024-05-31 01:19 UTC, merged