CN Configure Permission-Based Access Control
quinxii/AlumverseHcmusBackend pull request #51
Opened 2024-05-26 21:49 UTC by HuynhNguyen0811

2024-05-27 03:07 UTC, mugetsu0422 requested changes
nch là 2 cái Event với ParticipantEvent ko trả về quyền
chỉ trả về quyền cho comment

2024-05-27 03:07 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
> +	@DeleteMapping("/{id}/participants/{userId}")
```suggestion
	@PreAuthorize("hasAnyAuthority('Event.Participant.Delete'))
	@DeleteMapping("/{id}/participants")
```

2024-05-27 03:07 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
>  	@GetMapping("/{id}/comments")
có trả về quyền sao ko thấy file EventCommentPermission nhỉ

2024-05-27 03:07 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/repository/CommentEventRepository.java
> +	@Query(value = "select count(*) > 0 from comment_event where id = :commentId and creator = :userId", nativeQuery = true)
thêm đk is_delete = false

2024-05-27 12:34 UTC, HuynhNguyen0811 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
>  	@GetMapping("/{id}/comments")
có file CommentEventPermissions á

2024-05-27 12:41 UTC, HuynhNguyen0811 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
> +	@DeleteMapping("/{id}/participants/{userId}")
à cái này là tui để 2 trường hợp, 1 là admin đi kick participant do tui thấy có quyền Event.Participant.Delete trên db, 2 là participant tự out sự kiện á

2024-05-28 03:08 UTC, mugetsu0422 requested changes

2024-05-28 03:08 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java
> +	@DeleteMapping("/{id}/participants/{userId}")
quyền đó là để tự out đó ô :(
admin đi kick nghe kì quá, bên UI cũng ko có implement chức năng đó

2024-05-28 03:08 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/common/EventPermissions.java
ko dùng thì xóa đi ô

2024-05-28 03:08 UTC, mugetsu0422 commented on event-service/src/main/java/hcmus/alumni/event/common/ParticipantEventPermissions.java
như trên

2024-05-28 14:46 UTC, merged