CN Add notification tables to DB script
quinxii/AlumverseHcmusBackend pull request #71
Opened 2024-06-14 14:19 UTC by HuynhNguyen0811

Chắc là mình phải tạo 1 file excel để quy định entity type id

2024-06-14 14:20 UTC, HuynhNguyen0811 commented
Hồi đầu tui tưởng là Duy chỉnh cái này :( xong rồi nay tui nhận ra người cần chỉnh là tui

2024-06-14 14:39 UTC, mugetsu0422 requested changes
có cần phải tạo bảng cho entity và entity type để định nghĩa mấy cái đó ko🤔

2024-06-14 14:39 UTC, mugetsu0422 commented on database/script.sql
> +    actor_id INT UNSIGNED NOT NULL,
```suggestion
    actor_id VARCHAR(36) NOT NULL,
```
actor_id khóa ngoại tới user_id thì là này ô

2024-06-14 14:39 UTC, mugetsu0422 commented on database/script.sql
> +    status TINYINT NOT NULL,
status này là gì ô

2024-06-14 15:10 UTC, HuynhNguyen0811 commented
> có cần phải tạo bảng cho entity và entity type để định nghĩa mấy cái đó ko🤔

nếu mình thêm 1 bảng notification_entity_type với cột entity_type_id, description à. Nếu vậy thì vẫn cần excel để quy định notification message là gì nhỉ?

2024-06-14 15:29 UTC, mugetsu0422 commented
> > có cần phải tạo bảng cho entity và entity type để định nghĩa mấy cái đó ko🤔
> 
> nếu mình thêm 1 bảng notification_entity_type với cột entity_type_id, description à. Nếu vậy thì vẫn cần excel để quy định notification message là gì nhỉ?

ye, tạo excel đi ô

2024-06-14 15:29 UTC, mugetsu0422 approved these changes

2024-06-14 19:29 UTC, HuynhNguyen0811 commented
@mugetsu0422 
tui có tạo excel rồi mà không biết cái Entity type mình đếm như nào. Ông có nghĩ nên để entity_type là string không để có gì mình quy định như kiểu xxyy với xx là stt của service và yy là stt của entity trong service đó. Nếu được thì ông check file excel trong drive rồi quy định lại giúp tui

2024-06-15 04:17 UTC, mugetsu0422 commented
> @mugetsu0422 tui có tạo excel rồi mà không biết cái Entity type mình đếm như nào. Ông có nghĩ nên để entity_type là string không để có gì mình quy định như kiểu xxyy với xx là stt của service và yy là stt của entity trong service đó. Nếu được thì ông check file excel trong drive rồi quy định lại giúp tui

có thể tạo bảng `entity_type` như sau
```
id (Primary Key)
entity_table (Name of the entity table, e.g., posts, users, comments)
notification_type (Type of notification, e.g., New post created, New comment on a post, ...)
description (Description of the notification type)
```
sẽ liệt kê mỗi entity_table ra, rồi mỗi cái có những loại noti nào
id thì cứ `INT AUTO_INCREMENT` thôi
trong file excel thì sẽ chia ra thành các sheet services, mỗi services có entity_id nào liên quan thì ghi vô
vd như news sẽ có entity news_comment

2024-06-15 13:10 UTC, HuynhNguyen0811 commented
> > @mugetsu0422 tui có tạo excel rồi mà không biết cái Entity type mình đếm như nào. Ông có nghĩ nên để entity_type là string không để có gì mình quy định như kiểu xxyy với xx là stt của service và yy là stt của entity trong service đó. Nếu được thì ông check file excel trong drive rồi quy định lại giúp tui
> 
> có thể tạo bảng `entity_type` như sau
> 
> ```
> id (Primary Key)
> entity_table (Name of the entity table, e.g., posts, users, comments)
> notification_type (Type of notification, e.g., New post created, New comment on a post, ...)
> description (Description of the notification type)
> ```
> 
> sẽ liệt kê mỗi entity_table ra, rồi mỗi cái có những loại noti nào id thì cứ `INT AUTO_INCREMENT` thôi trong file excel thì sẽ chia ra thành các sheet services, mỗi services có entity_id nào liên quan thì ghi vô vd như news sẽ có entity news_comment

tui mới commit bảng entity_type với cũng mới chỉnh excel rồi á, có gì ông check lại giúp tui

2024-06-15 13:25 UTC, mugetsu0422 commented
@HuynhNguyen0811 thấy ok r á, h ghi vô sheet những hành động nào sẽ tạo thông báo đi ô
vd như trả lời 1 bình luận bên news và events
điền xong r thì gửi vô group cho mn check

2024-06-18 00:56 UTC, merged