Feature/nq user management
quinxii/AlumverseHcmusBackend pull request #76
Opened 2024-06-22 10:23 UTC by quinxii

- Update Login Api do thiếu try catch dẫn đến lỗi
- Update Sign up Api để set StatusId
- Forgot Password Api
- Verify reset code and Change Password
- Search Api
- Admin Update User Role Api

2024-06-24 03:04 UTC, mugetsu0422 requested changes
bữa thấy b có gửi file db vô group thêm table gì đó thì h qua nhánh feature/database sửa lại r tạo pr
nhớ có lần nhắn là chỉnh sửa file db trên github lun r mà

2024-06-24 03:04 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java
> +			@RequestParam(value = "orderBy", required = false, defaultValue = "lastLogin") String orderBy,
```suggestion
			@RequestParam(value = "orderBy", required = false, defaultValue = "fullName") String orderBy,
```
mặc định theo tên đi

2024-06-24 03:04 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/dto/ISearchDto.java
> +public interface ISearchDto {
```suggestion
public interface UserSearchDto {
```
trả về thêm avatar, roles của ng đó

2024-06-24 15:29 UTC, quinxii commented on auth-service/src/main/java/hcmus/alumni/authservice/controller/AuthController.java
> +		} catch (Exception e) {
bắt đúng là như thế nào á ông, ông muốn trả về Email ko hợp lệ và Mật khẩu ko hợp lệ à?
tui trả về Email hoặc mật khẩu ko hợp lệ vì ngta khuyên nên trả về chung chung như vậy để tránh việc bị hack đồ á ông hoặc tui có thể đổi thành Thông tin đăng nhập ko hợp lệ.

2024-06-24 16:42 UTC, mugetsu0422 commented on auth-service/src/main/java/hcmus/alumni/authservice/controller/AuthController.java
> +		} catch (Exception e) {
tức là catch đúng exception mà cái hàm đó nó ném ra
`catch (Exception e)` là sẽ bắt toàn bộ exception bất kể nó là gì vì phần lớn các exception trong Java đều kế thừa lớp này

2024-06-24 17:01 UTC, mugetsu0422 requested changes

2024-06-24 17:03 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java
> +			result.put("searchResult", searchResult.getContent());
@quinxii này chưa chỉnh lại nè

2024-06-25 12:55 UTC, mugetsu0422 approved these changes

2024-06-25 12:56 UTC, merged