CN notification
quinxii/AlumverseHcmusBackend pull request #77
Opened 2024-06-23 14:51 UTC by HuynhNguyen0811

Để chạy code cái Push Notification thì thêm file này vào https://drive.google.com/file/d/1seQ81HBCPvkFrB90xCdZFFhteZdV1Pfe/view?usp=sharing ngang hàng với file gcp-token.json + tắt Adblock
**API mới thêm cho notification**
1. User service
Thêm API để Get, Add, Delete User Subscription Token
2. Notification service (Service mới)
Thêm API để Get, Update status thành "Đã xem" cho notification

**API mới thay đổi để lưu notification vô DB và gửi push notification**
Ứng với mỗi service ở dưới thì tui thêm model + repository cho mấy cái bảng mới.  Ngoài ra thì tui thêm mấy cái file để gửi Push Notification bằng FCM bao gồm: 1 file config, 1 file service trong folder utils:
1. Event service
2. News service
3. Group service
4. Counsel service

2024-06-23 14:54 UTC, HuynhNguyen0811 commented
Chủ yếu là copy paste nên hơi nhiều file 🫠

2024-06-24 03:59 UTC, mugetsu0422 commented
> 1. User service
>    Thêm API để Get, Add, Delete User Subscription Token
đưa vô noti service đi ô, mỗi service phụ trách chức năng riêng, cái này liên quan tới noti nhiều hơn

2024-06-24 04:12 UTC, mugetsu0422 requested changes
request cái comment trc đó cái, phần code chưa đọc hết

2024-06-24 05:20 UTC, mugetsu0422 requested changes
Ngài🙇‍♂️
phần subscription như t nói ở trên thì đưa vô noti service
nó sẽ có url là notification/subscription

2024-06-24 05:20 UTC, mugetsu0422 commented on notification-service/src/main/java/hcmus/alumni/notification/config/GlobalExceptionHandler.java
> +        ErrorResponse error = new ErrorResponse(80000, "Tham số " + name + " bị thiếu");
```suggestion
        ErrorResponse error = new ErrorResponse(100000, "Tham số " + name + " bị thiếu");
```
noti service là service thứ 10

2024-06-24 05:20 UTC, mugetsu0422 commented on notification-service/src/main/java/hcmus/alumni/notification/controller/NotificationServiceController.java
> +		int totalUnreadMessages = notificationRepository.getUnreadNotificationsCount(userId);
```suggestion
		int totalUnreadNotification = notificationRepository.getUnreadNotificationsCount(userId);
```
noti chứ

2024-06-24 05:20 UTC, mugetsu0422 commented on notification-service/src/main/java/hcmus/alumni/notification/controller/NotificationServiceController.java
> +	    }
if else tới chết lun 😔
t thấy có điểm chung là ss `entityTable` và `notificationType`
thì ô có thể:
1. if theo `notificationType` trc
2. bên trong mỗi loại thì switch case `entityTable`

2024-06-24 05:22 UTC, mugetsu0422 commented
> https://drive.google.com/file/d/1seQ81HBCPvkFrB90xCdZFFhteZdV1Pfe/view?usp=sharing ngang hàng với file gcp-token.json + tắt Adblock

nhma sao phải tắt adblock v ô, noti ko work nếu có adblock à 😔

2024-06-24 05:47 UTC, HuynhNguyen0811 commented
> > https://drive.google.com/file/d/1seQ81HBCPvkFrB90xCdZFFhteZdV1Pfe/view?usp=sharing ngang hàng với file gcp-token.json + tắt Adblock
> 
> nhma sao phải tắt adblock v ô, noti ko work nếu có adblock à 😔

cái Adblocker Ultimate của tui xịn quá nó chặn cái push notification😔

2024-06-24 05:50 UTC, HuynhNguyen0811 commented on counsel-service/src/main/resources/application.properties
> +firebase.service.account.path=../service-account-key.json
nếu vậy thì đổi tên nó lại thành fcm-key.json

2024-06-24 05:59 UTC, mugetsu0422 commented on counsel-service/src/main/resources/application.properties
> +firebase.service.account.path=../service-account-key.json
v thêm vô gitignore ở root folder lun nha ô, cái mà ngang hàng với gcp-key.json

2024-06-24 13:20 UTC, mugetsu0422 requested changes

2024-06-24 13:20 UTC, mugetsu0422 commented on group-service/src/main/java/hcmus/alumni/group/controller/GroupServiceController.java
còn thiếu thông báo đối với yêu cầu phê duyệt được chấp thuận đk
mới thấy ô thêm thông báo cho creator và admin nếu có ng request còn đối với ng request thì chưa có thông báo nếu dc approved

2024-06-24 13:20 UTC, mugetsu0422 commented on group-service/src/main/java/hcmus/alumni/group/utils/FirebaseService.java
> +        }
thay bằng `@AllArgsConstructor` của lombok cho gọn

2024-06-25 02:23 UTC, mugetsu0422 approved these changes
🙇‍♂️
nhớ update file excel, ghi hướng dẫn nha ô

2024-06-25 14:44 UTC, merged