Feature/nq user profile
quinxii/AlumverseHcmusBackend pull request #87
Opened 2024-06-29 17:56 UTC by quinxii

User Profile API

2024-06-30 07:24 UTC, HuynhNguyen0811 commented on user-service/src/main/java/hcmus/alumni/userservice/model/AlumniModel.java
> +	}
hàm này để chi á, thấy truyền alumClass vô mà không làm gì

2024-06-30 07:48 UTC, quinxii commented on user-service/src/main/java/hcmus/alumni/userservice/model/AlumniModel.java
> +	}
oki tui xóa gòi nha

2024-06-30 12:58 UTC, mugetsu0422 requested changes

2024-06-30 12:58 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java
> +		}
```suggestion
```
vẫn trả về kq cho dù ko có job

2024-06-30 12:58 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java
> +	@GetMapping("profile/{id}/job/{jobId}")
```suggestion
	@GetMapping("/{id}/profile/job/{jobId}")
```

2024-06-30 12:58 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java
> +	@PostMapping("profile/{id}/create-job")
```suggestion
	@PostMapping("/profile/job")
```
bản thân method POST có nghĩa là tạo r
vì có userId trong request header r nên lược bỏ dc `{id}` trên url

2024-06-30 12:58 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java
> +	@PutMapping("profile/{id}/update-job/{jobId}")
```suggestion
	@PutMapping("profile/job/{jobId}")
```
lý do như trên

2024-06-30 12:58 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java
> +	@GetMapping("profile/{id}/education")
```suggestion
	@GetMapping("/{id}/profile/education")
```

2024-06-30 12:58 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java
> +		}
```suggestion
```
ko có thì vẫn trả về dù cho có trống

2024-06-30 12:58 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java
> +		result.put("edus", edus);
```suggestion
		result.put("education", edus);
```

2024-06-30 12:58 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java
> +	@GetMapping("profile/{id}/education/{educationId}")
```suggestion
	@GetMapping("/{id}/profile/education/{educationId}")
```

2024-06-30 12:58 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java
> +	@PostMapping("profile/{id}/create-education")
```suggestion
	@PostMapping("/profile/education")
```
lý do như api post job, avatar, cover

2024-06-30 12:58 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java
> +	@PutMapping("profile/{id}/update-education/{educationId}")
```suggestion
	@PutMapping("profile/education/{educationId}")
```
lý do như trên

2024-06-30 12:58 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java
> +	@GetMapping("profile/{id}/achievement")
```suggestion
	@GetMapping("/{id}/profile/achievement")
```

2024-06-30 12:58 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java
> +		}
```suggestion
```
vẫn trả về dù ko có

2024-06-30 12:58 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java
> +	@GetMapping("profile/{id}/achievement/{achievementId}")
```suggestion
	@GetMapping("/{id}/profile/achievement/{achievementId}")
```

2024-06-30 12:58 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java
> +	@PostMapping("profile/{id}/create-achievement")
```suggestion
	@PostMapping("/profile/achievement")
```

2024-06-30 12:58 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java
> +	@PutMapping("profile/{id}/update-achievement/{achievementId}")
```suggestion
	@PutMapping("profile/achievement/{achievementId}")
```

2024-06-30 12:58 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/repository/UserRepository.java
> +			+ "WHERE (:fullName IS NULL OR u.fullName LIKE :fullName%) "
```suggestion
			+ "WHERE (:fullName IS NULL OR u.fullName LIKE %:fullName%) "
```
`%` ở 2 đầu để query có thể nằm ở bất kì vị trí nào thay ví chỉ ở đầu. mấy cái search bên service khác đều theo cách này

2024-06-30 12:58 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/utils/ImageUtils.java
> +	}
```suggestion
	public String getAvatarPath() {
		return this.avatarPath;
	}
	
	public String getCoverPath() {
		return this.coverPath;
	}
```
tên file sẽ là userId lun như cái cmt ở api cover và avatar

2024-06-30 12:58 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java
> +		Optional<AlumniModel> optionalAlumni = alumniRepository.findByUserId(id);
hình như ở api `@PutMapping("/alumni-verification/{id}/verify")` chưa có tạo record cho bảng `alumni` nếu được approve á. b check lại giúp t nếu chưa có thì thêm giúp t nha

2024-07-01 02:47 UTC, mugetsu0422 requested changes

2024-07-01 02:47 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java
> +	@PreAuthorize("hasAnyAuthority('User.Edit')")
```suggestion
	@PreAuthorize("hasAnyAuthority('AlumniVerify.Edit')")
```

2024-07-01 02:47 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/dto/IAlumniProfileDto.java
trả về thêm studentId với begnningYear đi b

2024-07-01 02:47 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/repository/UserRepository.java
> +	           "u.email AS email, u.phone AS phone, u.aboutMe AS aboutMe " +
mấy này ghi gọn lại là `SELECT u` là dc r mà nhỉ, jpa sẽ tự động map từ UserModel sang IUserProfileDto

2024-07-01 02:52 UTC, mugetsu0422 commented on user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java
> +	@PutMapping("/alumni-verification/{id}")
```suggestion
	@PutMapping("/alumni-verification/{id}")
```
`{id}` ở đây là `userId` hay `id` của cái `verify_alumni` v
nếu là `userId` thì có thể lược bỏ

2024-07-01 13:13 UTC, merged